version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE}
    ports:
      - '5432:5432'
    network_mode: host
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis-cache
    ports:
      - '${REDIS_PORT}:6379'
    network_mode: host
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
